apiVersion: v1
kind: Service
metadata:
  name: voqal-backend
  namespace: voice-ai
  labels:
    app: voqal-backend
spec:
  selector:
    app: voqal-backend
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
  type: ClusterIP
